//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonerisPaymentIntegrationDataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMonerisTxnData
    {
        public long ID { get; set; }
        public string ResponseOrderID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string BankTransactionID { get; set; }
        public Nullable<decimal> ChargeTotal { get; set; }
        public string BankApprovalCode { get; set; }
        public string ResponseCode { get; set; }
        public string IsoCode { get; set; }
        public string Message { get; set; }
        public string TransName { get; set; }
        public string CardHolder { get; set; }
        public string F414 { get; set; }
        public string Card { get; set; }
        public string ExpiryDate { get; set; }
        public Nullable<int> Result { get; set; }
    }
}
